### ISSUE TITLE
need help on usage of the tool

### ISSUE THREAD

**Issue by lordlabakdas** [rycus86/prometheus_flask_exporter#51]
I have a flask app running at port 5006.

I have included the below information:

```
from prometheus_flask_exporter import PrometheusMetrics
metrics = PrometheusMetrics(app)
@app.route('/skip')
@metrics.do_not_track()
def skip():
    pass  # default metrics are not collected

@app.route('/<item_type>')
@metrics.do_not_track()
@metrics.counter('invocation_by_type', 'Number of invocations by type',
         labels={'item_type': lambda: request.view_args['type']})
def by_type(item_type):
    pass  # only the counter is collected, not the default metrics

@app.route('/long-running')
@metrics.gauge('in_progress', 'Long running requests in progress')
def long_running():
    pass

if __name__ == '__main__':
    app.debug = False
    app.run(host="0.0.0.0", port=5006)
@app.route('/status/<int:status>')
@metrics.do_not_track()
@metrics.summary('requests_by_status', 'Request latencies by status',
                 labels={'status': lambda r: r.status_code})
@metrics.histogram('requests_by_status_and_path', 'Request latencies by status and path',
                   labels={'status': lambda r: r.status_code, 'path': lambda: request.path})
def echo_status(status):
    return 'Status: %s' % status, status
```

I also have Prometheus running on a docker container on port 9090. I have Grafana pulling these events on a dashboard listening to events on http://localhost:9090.

I dont see the activity on Flask propagating to Prometheus and Grafana. Is there something I am missing in my setup?

**Comment by rycus86** [comment]
Hi!

Your example looks OK, just make sure the `if __name__ == '__main__':` block is at the end. If you hit http://localhost:5006/metrics does that return a response with a bunch of metrics?
If you do, check your Prometheus configuration if that's correct. If you can post the relevant bit here and perhaps describe your setup a bit, I can try to have a look a help maybe.

**Comment by lordlabakdas** [comment]
Yes, confirmed that the `if __name__ == '__main__':` block is at the end.

This is my POSTMAN snapshot for the '/metrics' API
![image](https://user-images.githubusercontent.com/1252659/81830112-adb84380-9509-11ea-891c-683336b97ba3.png)

But, the prometheus server (both using Docker or native) does not seem to be receiving the events:

```
./prometheus --config.file=prometheus.yml
level=info ts=2020-05-13T15:01:29.794Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-05-13T15:01:29.794Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.18.1, branch=HEAD, revision=ecee9c8abfd118f139014cb1b174b08db3f342cf)"
level=info ts=2020-05-13T15:01:29.794Z caller=main.go:338 build_context="(go=go1.14.2, user=root@2117a9e64a7e, date=20200507-17:00:35)"
level=info ts=2020-05-13T15:01:29.795Z caller=main.go:339 host_details=(darwin)
level=info ts=2020-05-13T15:01:29.795Z caller=main.go:340 fd_limits="(soft=2560, hard=unlimited)"
level=info ts=2020-05-13T15:01:29.795Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-05-13T15:01:29.799Z caller=main.go:678 msg="Starting TSDB ..."
level=info ts=2020-05-13T15:01:29.799Z caller=web.go:523 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-05-13T15:01:29.804Z caller=head.go:575 component=tsdb msg="Replaying WAL, this may take awhile"
level=info ts=2020-05-13T15:01:29.811Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=1
level=info ts=2020-05-13T15:01:29.811Z caller=head.go:624 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=1
level=info ts=2020-05-13T15:01:29.811Z caller=head.go:627 component=tsdb msg="WAL replay completed" duration=6.59897ms
level=info ts=2020-05-13T15:01:29.812Z caller=main.go:694 fs_type=19
level=info ts=2020-05-13T15:01:29.812Z caller=main.go:695 msg="TSDB started"
level=info ts=2020-05-13T15:01:29.812Z caller=main.go:799 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2020-05-13T15:01:29.852Z caller=main.go:827 msg="Completed loading of configuration file" filename=prometheus.yml
level=info ts=2020-05-13T15:01:29.852Z caller=main.go:646 msg="Server is ready to receive web requests."
```

The `prometheus.yml` file is as below:

```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

**Comment by rycus86** [comment]
OK, your Flask metrics are working OK then. The problem is that you haven't configured your Prometheus to scrape the Flask app, currently it only scrapes its own metrics.
Change the last section in the config like this:
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'flaskapp'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:5006']
```
